mkdir -p yaml_input
mkdir -p ancestral_gene
mkdir -p busco_annotation
mkdir -p gap_finder
mkdir -p gene_alignment
mkdir -p generate_genome
mkdir -p hic_mapping
mkdir -p insilico_digest
mkdir -p kmer
mkdir -p longread_coverage
mkdir -p nuc_alignments
mkdir -p pep_alignments
mkdir -p pretext_ingestion
mkdir -p punchlist
mkdir -p repeat_density
mkdir -p selfcomp
mkdir -p synteny
mkdir -p telo_finder
cp README.md yaml_input
cp README.md ancestral_gene
cp README.md busco_annotation
cp README.md gap_finder
cp README.md gene_alignment
cp README.md generate_genome
cp README.md hic_mapping
cp README.md insilico_digest
cp README.md kmer
cp README.md longread_coverage
cp README.md nuc_alignments
cp README.md pep_alignments
cp README.md pretext_ingestion
cp README.md punchlist
cp README.md repeat_density
cp README.md selfcomp
cp README.md synteny
cp README.md telo_finder
