mkdir -p yaml_input 
mkdir -p ancestral_gene 
mkdir -p busco_annotation 
mkdir -p gap_finder 
mkdir -p gene_alignment 
mkdir -p generate_genome 
mkdir -p hic_mapping 
mkdir -p insilico_digest 
mkdir -p kmer 
mkdir -p longread_coverage 
mkdir -p nuc_alignments 
mkdir -p pep_alignments 
mkdir -p pretext_ingestion 
mkdir -p punchlist 
mkdir -p repeat_density 
mkdir -p selfcomp 
mkdir -p synteny 
mkdir -p telo_finder 
